"""
Bosses for the game
"""

BOSS_LIST = [
    {
        "name": "Gwyn, Lord of Cinder",
        "enterance": "",
        "health": 10,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 16,
        "damage": 3,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Bed of Chaos",
        "enterance": "",
        "health": 20,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 5,
        "damage": 6,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Artorias the Abysswalker",
        "enterance": "",
        "health": 15,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 18,
        "damage": 3,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Nito, the First of the Dead",
        "enterance": "",
        "health": 12,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 15,
        "damage": 4,
        "drop": "",
        "souls": 500
    },
    {
        "name": "The Four Kings",
        "enterance": "",
        "health": 5,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 16,
        "damage": 5,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Seath the Scaleless",
        "enterance": "",
        "health": 8,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 18,
        "damage": 6,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Manus, Father of the Abyss",
        "enterance": "",
        "health": 15,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 18,
        "damage": 4,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Ornstein and Smough",
        "enterance": "",
        "health": 20,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 12,
        "damage": 3,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Midir, the Darkeater",
        "enterance": "",
        "health": 12,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 19,
        "damage": 4,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Lorian, Elder Prince",
        "enterance": "",
        "health": 18,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 12,
        "damage": 5,
        "drop": "",
        "souls": 500
    },
    {
        "name": "The Nameless King",
        "enterance": "",
        "health": 25,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 16,
        "damage": 3,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Abyss Watchers",
        "enterance": "",
        "health": 12,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 13,
        "damage": 2,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Pontiff Sulyvahn",
        "enterance": "",
        "health": 16,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 14,
        "damage": 2,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Slave Knight Gael",
        "enterance": "",
        "health": 27,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 15,
        "damage": 2,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Yhorm the Giant",
        "enterance": "",
        "health": 25,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 10,
        "damage": 5,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Sister Friede",
        "enterance": "",
        "health": 12,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 18,
        "damage": 4,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Champion Gundyr",
        "enterance": "",
        "health": 15,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 13,
        "damage": 2,
        "drop": "",
        "souls": 500
    },
    {
        "name": "The Curse-rotted Greatwood",
        "enterance": "",
        "health": 30,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 8,
        "damage": 2,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Vordt of the Boreal Valley",
        "enterance": "",
        "health": 12,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 15,
        "damage": 3,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Demon Prince",
        "enterance": "",
        "health": 18,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 12,
        "damage": 4,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Oceiros, the Consumed King",
        "enterance": "",
        "health": 16,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 16,
        "damage": 3,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Dragonslayer Armour",
        "enterance": "",
        "health": 20,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 16,
        "damage": 4,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Iudex Gundyr",
        "enterance": "",
        "health": 10,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 12,
        "damage": 2,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Old Demon King",
        "enterance": "",
        "health": 16,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 13,
        "damage": 4,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Lords of Cinder",
        "enterance": "",
        "health": 18,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 16,
        "damage": 3,
        "drop": "",
        "souls": 500
    }
]
