"""
Monsters for the game
"""

MONSTER_LIST = [
    {
        "name": "Hollow Soldier",
        "health": 2,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 3,
        "damage": 1,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Undead Dog",
        "health": 1,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 6,
        "damage": 1,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Asylum Demon",
        "health": 4,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 15,
        "damage": 2,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Silver Knight",
        "health": 3,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 4,
        "damage": 2,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Giant",
        "health": 4,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 8,
        "damage": 1,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Crystal Lizard",
        "health": 1,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 5,
        "damage": 1,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Darkwraith",
        "health": 4,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 7,
        "damage": 2,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Gravelord Servant",
        "health": 3,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 4,
        "damage": 1,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Hollow Archer",
        "health": 1,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 10,
        "damage": 1,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Fallen Knight",
        "health": 2,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 8,
        "damage": 1,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Cursed Hollow",
        "health": 1,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 6,
        "damage": 1,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Chained Prisoner",
        "health": 2,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 5,
        "damage": 1,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Gargoyle",
        "health": 3,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 12,
        "damage": 2,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Basilisk",
        "health": 3,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 7,
        "damage": 1,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Black Knight",
        "health": 6,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 14,
        "damage": 3,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Vagrant",
        "health": 3,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 13,
        "damage": 2,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Witch",
        "health": 1,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 8,
        "damage": 2,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Hollow Mage",
        "health": 1,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 6,
        "damage": 1,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Infant Wyrm",
        "health": 3,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 7,
        "damage": 2,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Plague Rat",
        "health": 1,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 4,
        "damage": 2,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Gravelord",
        "health": 5,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 10,
        "damage": 2,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Troll",
        "health": 3,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 9,
        "damage": 2,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Giant Spider",
        "health": 3,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 5,
        "damage": 1,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Dreg",
        "health": 1,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 2,
        "damage": 1,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Skeleton",
        "health": 1,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 4,
        "damage": 1,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Witch's Servant",
        "health": 3,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 6,
        "damage": 1,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Mimic",
        "health": 2,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 18,
        "damage": 5,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Abyssal Walker",
        "health": 4,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 12,
        "damage": 2,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Bloathead",
        "health": 1,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 7,
        "damage": 1,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Moss Giant",
        "health": 5,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 12,
        "damage": 2,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Dark Spirit",
        "health": 3,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 16,
        "damage": 4,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Hallowed",
        "health": 3,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 7,
        "damage": 1,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Giant Rat",
        "health": 1,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 6,
        "damage": 2,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Revenant",
        "health": 3,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 10,
        "damage": 1,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Ghoul",
        "health": 2,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 5,
        "damage": 1,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Hellkite Dragon",
        "health": 8,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 14,
        "damage": 4,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Lesser Demon",
        "health": 5,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 14,
        "damage": 2,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Skeletal Mage",
        "health": 1,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 6,
        "damage": 3,
        "drop": "",
        "souls": 500
    },
    {
        "name": "Bonewraith",
        "health": 3,
        "moveset": ['1', '2'],
        "grab": "",
        "hits": ['1', '2'],
        "attack": 7,
        "damage": 1,
        "drop": "",
        "souls": 500
    }
]
